---

- name: Check if keybase is installed
  command: dpkg-query -W keybase
  register: keybase_package_check_deb
  failed_when: keybase_package_check_deb.rc > 1
  changed_when: keybase_package_check_deb.rc == 1

- name: Download keybase
  get_url:
    url: https://prerelease.keybase.io/keybase_amd64.deb
    dest: "/home/{{ local_user }}/Downloads/keybase_amd64.deb"
  when: keybase_package_check_deb.changed

- name: Install keybase
  become: yes
  apt:
    deb: "/home/{{ local_user }}/Downloads/keybase_amd64.deb"
  when: keybase_package_check_deb.changed
