---

- name: Check if docker-credential-pass is installed
  stat:
    path: /usr/local/bin/docker-credential-pass
  register: stat_result

- name: Download docker-credential-pass
  become: yes
  unarchive:
    remote_src: yes
    src: https://github.com/docker/docker-credential-helpers/releases/download/v0.6.3/docker-credential-pass-v0.6.3-amd64.tar.gz
    dest: /usr/local/bin/
    mode: a+x
  when: not stat_result.stat.exists
