---

- name: Install apt packages
  become: yes
  apt:
    pkg:
      - alacarte
      - snapd
      - bat
      - fzf
      - gnome-shell-pomodoro  # https://community.spotify.com/t5/Desktop-Linux/Basic-controls-via-command-line/td-p/4295625
      - graphviz
      - htop
      - thefuck
      - neovim
      - tmux
      - tree
      - alacritty
      - zsh
      - appmenu-gtk3-module
      - gnome-tweaks
      - tlp
      # - network-manager-l2tp
      # - network-manager-l2tp-gnome
      - silversearcher-ag
      # For pyenv:
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncurses5-dev
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libffi-dev
      - liblzma-dev
      - python-openssl
      - git

- name: Build deps
  become: yes
  apt:
    pkg:
      - python3
    state: build-dep

- name: Remove apt packages
  become: yes
  apt:
    name:
      - code
      - falkon
      - kdeconnect
      - midori
      - fonts-powerline
      - kazam
      - slack
      - xl2tpd
    state: absent

# - name: Remove dependencies that are no longer required
#   become: yes
#   apt:
#     autoremove: yes
